name: Copilot Environment Setup

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup-copilot-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install validation dependencies
      run: |
        npm install
        echo "✅ Validation tools installed successfully"
        
    - name: Verify environment setup
      run: |
        echo "🔍 Verifying Copilot environment setup..."
        echo "Node.js version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Markdownlint CLI: $(npx markdownlint --version)"
        echo "Markdown Link Check: $(npx markdown-link-check --version)"
        
    - name: Test internet connectivity
      run: |
        echo "🌐 Testing external connectivity for link validation..."
        curl -I https://github.com || echo "⚠️ GitHub connectivity test failed"
        curl -I https://cloud.google.com || echo "⚠️ Google Cloud connectivity test failed"
        curl -I https://docs.aws.amazon.com || echo "⚠️ AWS Docs connectivity test failed"
        echo "✅ Connectivity tests completed"
        
    - name: Validate current documentation
      run: |
        echo "📝 Running documentation validation..."
        npx markdownlint README.md || echo "⚠️ Markdown linting found issues (expected for table formatting)"
        npx markdown-link-check README.md --config .markdown-link-check.json --progress || echo "⚠️ Some external links may be temporarily unavailable"
        echo "✅ Documentation validation completed"